name: salary_now_task
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^8.1.3
  # Networking
  dio: ^5.3.3
  # Pick PDF
  file_picker: ^6.1.1
  # Capture Selfie
  camera: ^0.10.5+5
  equatable: ^2.0.5
  dartz: ^0.10.1

  path_provider: ^2.1.1
  path: ^1.8.3
  # dependencies injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  freezed_annotation: ^2.4.1
  flutter_gen: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  freezed: ^2.4.5

flutter:

  uses-material-design: true
  generate: true

  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #         weight: 700

